<a href="https://colab.research.google.com/github/ManGata-Taa/Tugas-latihan-Praktikum/blob/main/latihan_praktikum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## import library numpy
import numpy as np

print("1. Matriks 3x3 dan tampilkan elemen tengahnya:  ")
matriks = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
print(matriks)
print("Elemen tengah:", matriks[1,1])

1. Matriks 3x3 dan tampilkan elemen tengahnya:  
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemen tengah: 5


In [2]:
print("\n2. Hitung jumlah seluruh elemen matriks:  ")
jumlah_elemen = np.sum(matriks)
print("Jumlah elemen:", jumlah_elemen)


2. Hitung jumlah seluruh elemen matriks:  
Jumlah elemen: 45


In [3]:
print("\n3. Buat tabel nilai 3 mahasiswa × 4 mata kuliah:  ")
nilai_mahasiswa = np.array([[85, 90, 78, 92],
                             [88, 95, 80, 91],
                             [89, 94, 87, 93]])
print(nilai_mahasiswa)


3. Buat tabel nilai 3 mahasiswa × 4 mata kuliah:  
[[85 90 78 92]
 [88 95 80 91]
 [89 94 87 93]]
